<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Base\Entity\City'                     => __DIR__.'/src/Base/Entity/City.php',
  'Base\Entity\Country'                  => __DIR__.'/src/Base/Entity/Country.php',
  'Base\Entity\LogEntry'                 => __DIR__.'/src/Base/Entity/LogEntry.php',
  'Base\Entity\Province'                 => __DIR__.'/src/Base/Entity/Province.php',
  'Base\Entity\Repository\City'          => __DIR__.'/src/Base/Entity/Repository/City.php',
  'Base\Entity\Repository\Country'       => __DIR__.'/src/Base/Entity/Repository/Country.php',
  'Base\Entity\Repository\Province'      => __DIR__.'/src/Base/Entity/Repository/Province.php',
  'Base\Entity\Repository\Session'       => __DIR__.'/src/Base/Entity/Repository/Session.php',
  'Base\Entity\Session'                  => __DIR__.'/src/Base/Entity/Session.php',
  'Base\Interfaces\MailServiceInterface' => __DIR__.'/src/Base/Interfaces/MailServiceInterface.php',
  'Base\Module'                          => __DIR__.'/src/Base/Module.php',
  'Base\Traits\EntityManagerTrait'       => __DIR__.'/src/Base/Traits/EntityManagerTrait.php',
  'Base\Traits\MailerTrait'              => __DIR__.'/src/Base/Traits/MailerTrait.php',
  'Base\Traits\MailServiceTrait'         => __DIR__.'/src/Base/Traits/MailServiceTrait.php',
  'Base\Traits\OptionsTrait'             => __DIR__.'/src/Base/Traits/OptionsTrait.php',
);
