<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Base\Entity\City'                          => __DIR__.'/src/Base/Entity/City.php',
  'Base\Entity\Country'                       => __DIR__.'/src/Base/Entity/Country.php',
  'Base\Entity\LogEntry'                      => __DIR__.'/src/Base/Entity/LogEntry.php',
  'Base\Entity\Province'                      => __DIR__.'/src/Base/Entity/Province.php',
  'Base\Entity\Repository\City'               => __DIR__.'/src/Base/Entity/Repository/City.php',
  'Base\Entity\Repository\Country'            => __DIR__.'/src/Base/Entity/Repository/Country.php',
  'Base\Entity\Repository\Province'           => __DIR__.'/src/Base/Entity/Repository/Province.php',
  'Base\Entity\Repository\Session'            => __DIR__.'/src/Base/Entity/Repository/Session.php',
  'Base\Entity\Session'                       => __DIR__.'/src/Base/Entity/Session.php',
  'Base\Factory\ElasticaClientFactory'        => __DIR__.'/src/Base/Factory/ElasticaClientFactory.php',
  'Base\Initializers\ElasticaInitializer'     => __DIR__.'/src/Base/Initializers/ElasticaInitializer.php',
  'Base\Interfaces\ElasticaAwareInterface'    => __DIR__.'/src/Base/Interfaces/ElasticaAwareInterface.php',
  'Base\Interfaces\MailServiceAwareInterface' => __DIR__.'/src/Base/Interfaces/MailServiceAwareInterface.php',
  'Base\Module'                               => __DIR__.'/src/Base/Module.php',
  'Base\Traits\ElasticaAwareTrait'            => __DIR__.'/src/Base/Traits/ElasticaAwareTrait.php',
  'Base\Traits\EntityManagerAwareTrait'       => __DIR__.'/src/Base/Traits/EntityManagerAwareTrait.php',
  'Base\Traits\MailerAwareTrait'              => __DIR__.'/src/Base/Traits/MailerAwareTrait.php',
  'Base\Traits\MailServiceAwareTrait'         => __DIR__.'/src/Base/Traits/MailServiceAwareTrait.php',
  'Base\Traits\OptionsAwareTrait'             => __DIR__.'/src/Base/Traits/OptionsAwareTrait.php',
);
