<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'user/password/forgot'                 => __DIR__.'/view/user/password/forgot.phtml',
    'user/password/mail/forgot'            => __DIR__.'/view/user/password/mail/forgot.phtml',
    'user/password/passwordchanged'        => __DIR__.'/view/user/password/passwordchanged.phtml',
    'user/password/reset'                  => __DIR__.'/view/user/password/reset.phtml',
    'user/password/sent'                   => __DIR__.'/view/user/password/sent.phtml',
    'user/registration/mail/set-password'  => __DIR__.'/view/user/registration/mail/set-password.phtml',
    'user/registration/mail/verify-email'  => __DIR__.'/view/user/registration/mail/verify-email.phtml',
    'user/registration/set-password'       => __DIR__.'/view/user/registration/set-password.phtml',
    'user/registration/verify-email-error' => __DIR__.'/view/user/registration/verify-email-error.phtml',
    'zfc-user/user/login'                  => __DIR__.'/view/zfc-user/user/login.phtml',
);
