<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Application\Controller\Factory\YumlControllerFactory' => __DIR__.'/src/Application/Controller/Factory/YumlControllerFactory.php',
  'Application\Controller\IndexController'               => __DIR__.'/src/Application/Controller/IndexController.php',
  'Application\Module'                                   => __DIR__.'/src/Application/Module.php',
);
