<?php echo $this->doctype() ?>

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
    
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('description', '')
            ->appendName('author', '')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/vendor.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/conditionals.js', 'text/javascript', ['conditional' => 'lt IE 9']) ?>
    </head>
    <body>
        <div class="container">
            <?php echo $this->content ?>
        </div>
        
        <!-- Inline Scripts -->
        <?php echo $this->inlineScript()
            ->prependFile('/js/vendor.js')
            ->prependFile($this->basePath() . '/js/vendor/modernizr.min.js')?>
    </body>
</html>
